apium-graveolens/buynCel

package.json
=> added npm init

.gitignore, client/components/Main.js, client/index.js, package-lock.json, package.json, public/index.html, webpack.config.js
The commits are pretty self explanatory.
=> Front end scaffolding

api/index.js, package-lock.json, package.json, server.js
=> added basic api routes 

api/checkAdmin.js, api/index.js, api/lineitems.js, api/orders.js, api/products.js, api/users.js
- Auth added to all necessary api routes. Some routes (like GET /products) not locked down as there is no need.
-Auth routes will check if (1) the user is an admin or (2) the user is looking to access/update their own data, and allow access to the route only if one of the above is true. (ex: user 2 can only access/update data for user 2, admins can access/update all data.)
-Had it working locally with a test db, but variable names etc. will probably need to be updated at some point to reflect actual db naming/structure
=> auth added to api routes

test/store-orders.spec.js, test/store-products.spec.js
Very similar to Products test. Ran into issues with axios-mock-adapter when trying to run both test files at the same time. This was fixed by the changes made to test/store-products.spec.js.
=> Orders reducer test - closes #52

package.json, test/store-auth.spec.js
Last test is temporary. Need to think of a better way to write it. Also this doesn't test logout functionality.
=> Auth reducer test - closes #58

db/connection.js, db/index.js, test/model-user.spec.js
Sequelize looks for a db named 'celery-test' if not otherwise specified as an env variable
=> User model test - closes #63

db/index.js, db/models/Review.js
Still need to explicitly set that there is no maximum character count for the content field, only a minimum.
=> Add review model and associations - closes # 34

client/components/Main.js, client/components/SignUp.js, package.json
Barebones of the "Sign Up" page. Also added some material ui setup.
=> Create account page - closes #14

client/components/Main.js, client/components/ProductDetail.js, client/components/ProductList.js, db/models/Product.js, package.json
- Update Product model so that price is a float, not an int
- Add product detail view
- Update start script so that nodemon ignores changes to non-server files
- Add withRouter wrapper to Main component so that route changes can **prop**agate down to children. More info => [https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md](url)
=> Product details - closes #4

client/components/Main.js, client/components/NavBar.js, package.json, public/index.html, public/main.css
- Add Navbar with visitor links
- Add general stylesheet to public folder
Todo: 
- Add cart link
- Add logged in user links
=> Add navbar and some general style

api/categories.js, api/lineitems.js, api/products.js, db/index.js, package-lock.json
- api + db should be synced now, but if any bugs come up when linking with the front end let me know
=> Api tweaks

api/products.js, client/components/ProductDetail.js, client/components/ProductList.js, client/components/ProductSingle.js
=> Style product list

.gitignore, api/auth.js, db/index.js, db/models/User.js, package-lock.json
- Added facebook oauth api routes / functionality
- Runs locally on my machine, but won't from the repo since (1) the .env file is not included in the repo, and (2) facebook appears to require https to make the oauth app public. (LocalHost doesn't run in https by default.) 
- Might have to fix these when it's deployed, but for now it runs locally.
=> added facebook oauth api

db/index.js, db/models/Review.js
- Added categories and reviews to seed function
- Added category and review relationships
- Added rating field (1-5) to review model
=> Update seed data

api/users.js, db/index.js, db/models/Order.js, db/models/Product.js
Did a quick review of the functionality we're supposed to have, and it looks like some things still need to be worked on in regards to db and api. Got working on some of these per below:
Admins need to delete users -> added user delete auth route for admins only
Only "in stock" quantities should show when users browse store -> added required quantity field to product model, updated seed data
Order status needs to be either "created, processing, cancelled, or completed", and also user should be able to browse with a "cart" and get an email once order is shipped ("completed") and "delivered" -> cart model status field updated to reflect the above statuses, seed data updated
Will continue to work on other api + db fine tuning tomorrow - search for product, add shipping address to orders, add …
=> fine tuning of api db

client/components/Login.js, client/components/Main.js, client/components/NavBar.js, client/store/auth.js, client/store/index.js
Added login page and some related functionality
=> Add login page

api/orders.js, client/components/ProductList.js, client/components/ProductSingle.js, client/store/orders.js
=> Add lineitem functionality

api/lineitems.js, client/components/Cart.js, client/components/Main.js, client/components/ProductDetail.js, client/store/index.js, client/store/lineItems.js, client/store/orders.js, db/index.js
No Cart link yet, have to go to the url manually.
=> Add cart view

db/models/LineItem.js
Updated lineItem model to reflect the below requirement.
_If a user completes an order, that order should keep the price of the item at the time when they checked out even if the price of the product later changes._
The lineItem model now includes the field "salePrice" that should be updated when the cart transitions to order status with a static value for the product price at that time
=> added salePrice to listItem model

api/auth.js, api/orders.js, db/models/Order.js, package-lock.json, package.json
Started integrating Stripe on the back-end.
- added "isPaid" field on the order model to mark order as paid if Stripe charge goes through
- POST order api will attempt to pay with stripe if that option is requested on req.body using an order instance
- order instance works with test data only for now
=> started stripe integration with test data

db/index.js, db/models/Product.js, package-lock.json
- single picture functionality integrated with front end
- multiple picture functionality probably needs more time to set up / integrate
=> single product pic functionality added
